openapi: 3.0.0
info:
  title: EstateCraft API
  version: 1.0.0
  description: API documentation for EstateCraft Real Estate Management Platform
servers:
  - url: https://realestate-9evw.onrender.com/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []